version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: football_db_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: football_db     
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: root       
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    restart: always